# Uses No Autoencoder
do_train: True
do_valid: True
do_test: True
evaluate_train: True
countries: False
data_path: "./data/mquake"
model: "TransE"
double_entity_embedding: false
double_relation_embedding: false
negative_sample_size: 128
hidden_dim: 500
gamma: 12
negative_adversarial_sampling: True
adversarial_temperature: 1.0
batch_size: 1024
regularization: 0.0
test_batch_size: 16
uni_weight: true
learning_rate: 0.0001
cpu_num: 12
save_path: "models/graph_embeddings/mquake"
max_steps: 100000
save_checkpoint_steps: 10000
valid_steps: 10000
log_steps: 100
test_log_steps: 1000
autoencoder_flag: False
wandb_project: "mquake_embeddings"
track: True
random_seed: 42
