program: kge_launcher.py
project: fb15k-237
method: bayes

command:
  - python
  - kge_launcher.py

metric:
  name: Valid_BASIC_HITS@1  # (higher is better)
  goal: maximize  # Higher is better

parameters:
  mode:
    value: train

  model:
    value: TransE

  dataset:
    value: FB15k-237

  gpu_id:
    value: 0

  seed:
    value: 0

  batch_size:
    distribution: q_log_uniform_values
    q: 1
    min: 1
    max: 32

  negative_sample_size:
    distribution: q_uniform
    q: 1
    min: 1
    max: 16

  hidden_dim:
    distribution: q_log_uniform_values
    q: 50
    min: 50
    max: 200

  gamma:
    distribution: uniform
    min: 0.5
    max: 24.0

  alpha:
    distribution: uniform
    min: 0.1
    max: 1.0

  lambda_lp:
    distribution: uniform
    min: 0.01
    max: 1.0
  
  lambda_rp:
    distribution: uniform
    min: 0.01
    max: 1.0
  
  lambda_dp:
    distribution: uniform
    min: 0.01
    max: 1.0
  
  lambda_nbe:
    distribution: uniform
    min: 0.01
    max: 1.0
  
  lambda_nbr:
    distribution: uniform
    min: 0.01
    max: 1.0

  learning_rate:
    distribution: q_log_uniform_values
    q: !!float 1e-05
    min: !!float 2e-05
    max: !!float 8e-04

  max_steps:
    distribution: q_log_uniform_values
    q: 25000
    min: 50000
    max: 150000

  task:
    values: [all, basic, wild]  # Options: link_prediction, relation_prediction, all

  valid_steps:
    value: 10000

  test_batch_size:
    value: 16

  clean_up:
    value: true  # Clean up the model directory after training

  wandb_project:
    value: fb15k-237  # Your wandb project name

  track:
    value: true  # Always track with wandb

  saving_metric:
    value: HITS@1  # Metric to save the best model
  
  saving_threshold:
    value: 0.30  # Threshold for saving the best model

  # (Optional) Positional argument 16+
  additional_params:
    value: ""  # Empty unless you add extra flags like -de, -dr
