data_dir: "data/KinshipHinton"
model: "TransE"
trained_model_path: "models/TransE_KinshipHinton_dim12"
nav_epsilon_error: 1.32
nav_epsilon_metric: "l2"
#freebaseqa_path: "data/KinshipHinton/kinship_hinton_qa_1hop"
raw_QAData_path: "data/KinshipHinton/kinship_hinton_qa_1hop.csv"
cached_QAMetaData_path: "./.cache/itl/kinship_hinton_qa_1hop.json"
rl_gamma: 0.9
nav_start_emb_type: "relevant"
num_rollout_steps: 2
batch_size: 6
batch_size_dev: 2
batches_b4_eval: 1
node_data_path: ""
node_data_key: ""
relationship_data_path: ""
relationship_data_key: ""
