program: nav_supervised_training.py
project: kinship-hinton-multihop
method: bayes

command:
  - ${env}
  - python
  - nav_superviced_training.py
  - --preferred_config=""
  - --seed=420
  - --wandb
  - --wr_notes=2-hop task - Navigation Agent for MultiHopKG with Supervised Learning
  - --wandb_project=kinship-hinton-multihop  # Your wandb project name

metric:
  name: valid/hits_1  # (higher is better)
  goal: maximize  # Higher is better

parameters:
  learning_rate:
    distribution: log_uniform_values
    min: 1e-8
    max: 1e-1
  rl_gamma:
    distribution: uniform
    min: 0.9
    max: 0.99
  beta:
    distribution: uniform
    min: 0.01
    max: 0.1
    
  supervised_adapter_scalar:
    distribution: log_uniform_values
    min: 1e-6
    max: 1e0
  supervised_sigma_scalar:
    distribution: log_uniform_values
    min: 1e-6
    max: 1e0
  supervised_expected_sigma:
    distribution: log_uniform_values
    min: 1e-6
    max: 1e0

  epochs:
    distribution: q_log_uniform_values
    q: 10
    min: 10
    max: 150  
  num_rollouts:
    value: 0
  num_rollout_steps:
    values: [2, 3, 4, 5, 6]

  batch_size:
    distribution: q_log_uniform_values
    q: 1
    min: 1
    max: 16
  batch_size_dev:
    value: 8

  data_dir:
    value: data/KinshipHinton
  raw_QAData_path: 
    value: data/KinshipHinton/kinship_hinton_qa_2hop.csv
  cached_QAMetaData_path: 
    value: ./.cache/itl/kinship_hinton_qa_2hop.json
  node_data_path:
    value: ""
  node_data_key: 
    value: ""
  relationship_data_path: 
    value: ""
  relationship_data_key:
    value: ""

  model:
    value: TransE
  trained_model_path: 
    value: models/TransE_KinshipHinton_dim12
  
  nav_start_emb_type:
    value: relevant
  nav_epsilon_error: 
    value: 1.00